version: '3'

services:
  db:
    image: mdillon/postgis
    environment:
      POSTGRES_PASSWORD: geoq
      POSTGRES_USER: geoq
      POSTGRES_DB: geoq

  web:
    image: centos7
    build: .
    volumes:
      - /usr/local/src/geoq/geoq:/usr/src/geoq
    ports:
      - "8000:80"
    command: sh -c 'python app.py'
    depends_on:
      - db