version: '3'

services:
  db:
    image: mdillon/postgis
    environment:
      POSTGRES_PASSWORD: geoq
      POSTGRES_USER: geoq
      POSTGRES_DB: geoq

  web:
    build: .
    volumes:
      - /usr/local/src/geoq/geoq:/usr/src/geoq
    ports:
      - "8000:8000"
    depends_on:
      - db
    command: ["./wait-for-postgres.sh", "db:5432", "python", "app.py"]