version: '3'

services:
  db:
    image: mdillon/postgis
    environment:
      POSTGRES_PASSWORD: geoq
      POSTGRES_USER: geoq
      POSTGRES_DB: geoq

  web:
    image: stephenrjones/geoq-django10:production
    ports:
      - "8000:80"
    depends_on:
      - db