version: '3'

services:
  db:
    image: mdillon/postgis
    environment:
      POSTGRES_PASSWORD: geoq
      POSTGRES_USER: geoq
      POSTGRES_DB: geoq

  web:
    image: stephenrjones/geoq-django10
    ports:
      - "80:80"
    command: sh -c './wait-for db:5432 -- python app.py'
    depends_on:
      - db